# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81a601cf3ae3606e60361b9baf0c262b7172c8192902c40148e8e7bfc5f54cd78b265511897ad5659d7ae3ef4651c8e69444a2a1e451d35036de53ee2641f94

test:
  secret_key_base: 3cdee8ebadeab92632f002fb5e90e3b5f57fadad58e189533de2791a46d66e9d8528f3c0d2d2949d98c23f48be2607a26e5cbdc738848b616eabbc84d0fe02f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
